# Generated by Django 5.0.4 on 2024-04-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('personal_email', models.EmailField(max_length=254, unique=True)),
                ('locker_number', models.IntegerField(unique=True)),
                ('locker_combination', models.IntegerField()),
                ('good_student', models.BooleanField(default=False)),
            ],
        ),
    ]
