# Generated by Django 5.0.4 on 2024-04-23 23:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='captured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='date_captured',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='date_encountered',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='Unknown'),
        ),
    ]
